### ISSUE TITLE
Why did you not release the source code?

### ISSUE THREAD

**Issue by ghost** [phtom/WCRipper#1]
> Why i will not release the source code? A: Because last time i made a useful project a guy copied my code, got 2 interviews using MY CODE and got 2 million downloads and the credits.

You should put a restrictive license like GPL on it then.

Then no one can legally copy you, and gpl-violations.org is always looking for violations. :smiley:

**Comment by phtom** [comment]
Hi, the source code is live for everyone, i gave up on the idea of not releasing it. Its online and now under GPL 3.0 license :D

**Comment by ghost** [comment]
What project of yours got copied? Just asking out of curiosity.
